# fly.toml app configuration file generated for prox-chat-tk on 2025-05-25T17:33:35+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prox-chat-tk'
primary_region = 'lax'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # keep running for websocket connections
  auto_start_machines = true
  min_machines_running = 1    
  max_machines_running = 1    # single instance
  processes = ['app']
  
  # websocket-specific configuration
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000        
    soft_limit = 800         

  # health checks disabled - websocket server handles them by gracefully failing handshake
  # fly.io will consider the service healthy if it can connect to the port

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# environment variables for the rust server
[env]
  RUST_LOG = "info"        

# deploy configuration
[deploy]
  strategy = "immediate"    
